<html>
<div class="header">
  <div class = "logo">
    <img src="../images/logo_s_blank.png">
  </div>
  
  <div class = "navLinkBox">
    <a class="navLink" href="../"> Home </a>
    <a class="navLink" href=""> Games </a>
    <a class="navLink" href="../about"> About </a>
    <!--<a class="navLink" href="wiki"> Wiki </a>-->
  </div>
  <h2 class = "name"> T-17 Heavy Industries </h1>
</div>
</html>